name: 'Upload package to Cloudsmith'
description: 'Uploaded packages in provided path to Cloudsmith'
inputs:
  repo:
    description: 'Cloudsmith repository'
    required: true
  dist:
    description: 'Distribution to target (as shown in cloudsmith list distros deb)'
    required: true
  path:
    description: 'Where to look for packages'
    required: true
  CLOUDSMITH_API_KEY:
    description: 'Cloudsmith API key'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
