name: 'Build conan package'
description: 'Build a conan package and upload it'
inputs:
  package:
    description: 'Package name (e.g. MyPackage)'
    required: true
  user:
    description: 'Bintray user'
    required: true
  repository:
    description: 'Bintray repository'
    required: true
  stable-channel:
    description: 'Stable channel for uploads'
    required: true
    default: 'stable'
  dev-channel:
    description: 'Development channel for uploads'
    required: true
    default: 'dev'
  with-build-type:
    description: 'True if the recipe supports build_type then build Debug and Release'
    required: true
    default: false
  force-upload:
    description: 'Upload the package regardless of the branch'
    required: true
    default: false
  working-directory:
    description: 'Change working directory'
    required: true
    default: ''
  version:
    description: 'Force a version (otherwise extract it from conanfile.py'
    required: true
    default: ''
  with-docker:
    description: 'If true this action will also build the package in the requested docker-images'
    required: true
    default: false
  docker-images:
    description: 'If with-docker is true then extra packages are built for these images'
    required: true
    default: ''
  BINTRAY_API_KEY:
    description: 'Bintray API key'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
