name: 'Build package'
description: 'Build a Debian/Ubuntu package using a provided recipe'
inputs:
  dist:
    description: 'Debian/Ubuntu distribution to target'
    required: true
  arch:
    description: 'Architecture to target'
    required: true
  recipe:
    description: 'Recipe to use to build your package (absolute path)'
    required: true
  ros-distro:
    description: 'ROS distribution you require to build your package. If empty, no ROS mirror is added'
    required: true
    default: ''
  other-mirrors:
    description: 'Extra mirrors to setup (space separated)'
    required: true
    default: ''
  other-gpg-keys:
    description: 'Extra signing keys to accept'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
