name: Test install-dependencies action
on: [push,pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Test install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: clang
        ubuntu: |
          apt: libeigen3-dev libspacevecalg-dev
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
        macos: |
          brew-taps: mc-rtc/mc-rtc
          brew: eigen spacevecalg
          pip: Cython coverage nose numpy
        windows: |
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7

