name: Test setup-pbuilder action
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Test setup-pbuilder
      uses: jrl-umi3218/github-actions/setup-pbuilder@master
      with:
        dist: xenial
        arch: amd64
        ros-distro: kinetic
        other-mirrors: https://dl.bintray.com/gergondet/multi-contact-head
        other-gpg-keys: "0x892EA6EE273707C6495A6FB6220D644C64666806"
